name: CI

on:
  push:
    branches: [main, "dev/*"]
  pull_request:
    branches: [main, "dev/*"]

jobs:
  ci:
    uses: brig-id/.github/.github/workflows/ci-rust.yml@29c29dc061b5405f6fb33281e675613f0302899d
    with:
      working-directory: .

  security:
    uses: brig-id/.github/.github/workflows/security-audit.yml@29c29dc061b5405f6fb33281e675613f0302899d
    with:
      working-directory: .
